### ISSUE TITLE
Ability to execute custom generator

### ISSUE THREAD

**Issue by sethfischer** [florianfesti/boxes#602]
## Proposal

Add the ability to execute a [custom generator](https://florianfesti.github.io/boxes/html/api_generator.html).

## Use case

I keep a record of commands used by maintaining an [invoke](https://www.pyinvoke.org/) `tasks.py` file. Others may maintain a `Makefile` to keep a record of their boxes.py builds.

In either case, boxes.py would be installed into a virtual environment using [pip](https://pip.pypa.io/en/stable/), [Poetry](https://python-poetry.org/), or any other Python package manager (see example below). This has the advantage of pinning a specific version of boxes.py and dependencies to ensure reproducible output.

When installed in this manner is it not convenient to add custom generators alongside the bundled generators (which are in a managed virtual environment).

I would like to add [custom generators](https://florianfesti.github.io/boxes/html/api_generator.html) to this project, say in a `my_generators/` directory.

## Proposed solution

Add the ability to execute custom generators from the `boxes` executable script, for example:

```
boxes MyGenerator --generators-dir="path/to/my_generators/" [boxes default arguments]... [my generator arguments]...
```

or similar.

## Example of installing boxes with a package manager

An example Poetry `[tool.poetry.dependencies]` table from [sethfischer/boxes-builds](https://github.com/sethfischer/boxes-builds):

```toml
[tool.poetry.dependencies]
python = "^3.9"
boxes = {git = "https://github.com/florianfesti/boxes.git", rev = "2ab7fc909eec106af17bad9347289c07e626277c"}
invoke = "^2.0.0"
```
